/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalistaRouteImport } from './routes/analista'
import { Route as BancaRouteImport } from './routes/banca'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as LoginRouteImport } from './routes/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaRoute = AnalistaRouteImport.update({
  id: '/analista',
  path: '/analista',
  getParentRoute: () => rootRouteImport,
} as any)
const BancaRoute = BancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRoute
  '/banca': typeof BancaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRoute
  '/banca': typeof BancaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRoute
  '/banca': typeof BancaRoute
  '/chat': typeof ChatRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analista' | '/banca' | '/chat' | '/clientes' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analista' | '/banca' | '/chat' | '/clientes' | '/login'
  id:
    '__root__' | '/' | '/analista' | '/banca' | '/chat' | '/clientes' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalistaRoute: typeof AnalistaRoute
  BancaRoute: typeof BancaRoute
  ChatRoute: typeof ChatRoute
  ClientesRoute: typeof ClientesRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista': {
      id: '/analista'
      path: '/analista'
      fullPath: '/analista'
      preLoaderRoute: typeof AnalistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banca': {
      id: '/banca'
      path: '/banca'
      fullPath: '/banca'
      preLoaderRoute: typeof BancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalistaRoute: AnalistaRoute,
  BancaRoute: BancaRoute,
  ChatRoute: ChatRoute,
  ClientesRoute: ClientesRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
